pagination:
  subjects_per_page: 2
  users_per_page: 5
  exams_per_page: 10
  questions_per_page: 10
exam:
  questions_per_exam: 10
  time_in_minutes: 10
  sec: 60
  option:
    - uncheck
    - checked
    - all
  all: "all"
questions:
  options:
    - all
    - waiting
    - approved
    - edited
  all: "all"
  type:
    single: single
    multiple: multiple
    text: text
