pagination:
  subjects_per_page: 2
  users_per_page: 5
exam:
  questions_per_exam: 10
  time_in_minutes: 10
  sec: 60
questions:
  options:
    - all
    - waiting
    - approved
    - edited
  all: "all"
